"""
Django settings for StudentCompanion project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import importlib.util

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)x_iiq9%b(zpq(6%0y0h*vhu^)6ym(y21!tie87_e*#*kmcg*&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["crunodal-libbie-preconsciously.ngrok-free.dev","127.0.0.1",
    "localhost"]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'rest_framework',
    'channels',
    'Login',
    'Questionaire_project',
]

# Allow local development to run even if Daphne is not installed in the active interpreter.
# Channels will still work with Django's dev server for local testing.
if importlib.util.find_spec("daphne") is not None:
    INSTALLED_APPS.insert(0, "daphne")


SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            # Force Google to issue/refresh offline token deterministically.
            'access_type': 'offline',
            'prompt': 'consent',
            'include_granted_scopes': 'true',
        },
        'APP': {
            'client_id': "799103574658-8kdno7qkq5j2pgd03t3jf4ooa5l6s576.apps.googleusercontent.com",
            'secret': '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',
            'key': ''
        }
    }
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]


ROOT_URLCONF = 'StudentCompanion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

WSGI_APPLICATION = 'StudentCompanion.wsgi.application'
ASGI_APPLICATION = 'StudentCompanion.asgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Student_Companion35',
        'USER': 'postgres',
        'PASSWORD': 'muskan',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# MEDIA FILES CONFIGURATION
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_STORE_TOKENS = True

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# for getting recovery email in gmail
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "mallahkhadija97@gmail.com"
EMAIL_HOST_PASSWORD = "grah kehi eslf nuch"

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

REDIS_URL = os.getenv("REDIS_URL", "").strip()
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": 300,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "student-companion-local-cache",
            "TIMEOUT": 300,
        }
    }

EMOTION_ANALYZE_INTERVAL_SECONDS = 1.0
EMOTION_MAX_RECONNECT_ATTEMPTS = 5
EMOTION_FRAME_JPEG_QUALITY = 0.7
EMOTION_MAX_IMAGE_BYTES = 1500000
EMOTION_MAX_ENCODED_IMAGE_BYTES = 2200000
EMOTION_MAX_PIXELS = 2073600  # 1920x1080
EMOTION_MAX_WIDTH = 1920
EMOTION_MAX_HEIGHT = 1080
EMOTION_MIN_BRIGHTNESS = 20
EMOTION_MAX_BRIGHTNESS = 235
EMOTION_MIN_BLUR_VARIANCE = 35.0
EMOTION_MIN_FACE_CONFIDENCE = 0.55
EMOTION_INFERENCE_TIMEOUT_SECONDS = 6.0
EMOTION_INFERENCE_MAX_MEMORY_MB = 512
EMOTION_WORKER_RESTART_TIMEOUT_THRESHOLD = 3
EMOTION_CIRCUIT_BREAKER_FAILURES = 5
EMOTION_CIRCUIT_BREAKER_OPEN_SECONDS = 20.0
EMOTION_HEARTBEAT_INTERVAL_SECONDS = 15
EMOTION_HEARTBEAT_GRACE_SECONDS = 90
EMOTION_HEARTBEAT_CHECK_SECONDS = 5
EMOTION_ENFORCE_PING_TIMEOUT = True
EMOTION_MAX_CONNECTIONS_PER_IP = 4
EMOTION_MAX_CONNECTIONS_PER_ASSESSMENT = 1
EMOTION_MAX_FRAMES_PER_ASSESSMENT_WINDOW = 120
EMOTION_FRAME_QUOTA_WINDOW_SECONDS = 60
EMOTION_CONNECTION_TTL_SECONDS = 120
EMOTION_FACE_TRACK_IOU_THRESHOLD = 0.25
EMOTION_CLIENT_MAX_FRAME_WIDTH = 640
EMOTION_CLIENT_MAX_ENCODED_BYTES = 900000
EMOTION_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
EMOTION_ALLOWED_ORIGIN_SUFFIXES = [
    ".ngrok-free.dev",
    ".ngrok.io",
]
ASSESSMENT_MAX_ANSWER_CHARS = 5000
