from django.contrib import admin

from .models import Answer, Assessment, EmotionRecord, Question, ScaleEmotionSession
from .models import MSEReport
from .models import AnalysisResult 


@admin.register(Question)
class QuestionAdmin(admin.ModelAdmin):
    list_display = ("id", "mse_category", "is_final", "is_active")
    list_filter = ("is_final", "is_active", "mse_category")
    search_fields = ("question_text", "video_file")


@admin.register(Assessment)
class AssessmentAdmin(admin.ModelAdmin):
    list_display = ("id", "user", "session_key", "is_completed", "created_at")
    list_filter = ("is_completed", "created_at")
    search_fields = ("session_key", "user__email", "user__username")


@admin.register(Answer)
class AnswerAdmin(admin.ModelAdmin):
    list_display = ("id", "assessment", "question", "updated_at")
    list_filter = ("question", "created_at")
    search_fields = ("answer_text",)


@admin.register(EmotionRecord)
class EmotionRecordAdmin(admin.ModelAdmin):
    list_display = (
        "id",
        "assessment",
        "scale",
        "question",
        "status",
        "dominant_emotion",
        "confidence",
        "created_at",
    )
    list_filter = ("scale", "status", "dominant_emotion", "created_at")
    search_fields = ("assessment__id", "question__id", "frame_id")


@admin.register(ScaleEmotionSession)
class ScaleEmotionSessionAdmin(admin.ModelAdmin):
    list_display = (
        "id",
        "assessment",
        "scale",
        "started_at",
        "ended_at",
        "total_frames",
        "overall_dominant_emotion",
        "distress_ratio",
    )
    list_filter = ("scale", "started_at", "ended_at")
    search_fields = ("assessment__id",)

@admin.register(MSEReport)
class MSEReportAdmin(admin.ModelAdmin):
    list_display = ['assessment', 'generated_at', 'updated_at']
    readonly_fields = ['generated_at', 'updated_at']


@admin.register(AnalysisResult)
class AnalysisResultAdmin(admin.ModelAdmin):
    list_display = [
        "assessment",
        "depression_level",
        "anxiety_level",
        "stress_level",
        "overall_trend",
        "has_therapist_script",
        "updated_at",
    ]
    readonly_fields = [
        "assessment",
        "created_at",
        "updated_at",
        "therapist_script",          # <── view it here, read-only
        
        "recommendations_json",
        "scale_emotions",
        "facial_note",
        "comparison_results",
        "comparison_summary",
        "overall_trend",
        "emotion_labels",
        "dominant_emotion",
        "emotional_summary",
    ]
    fieldsets = [
        ("Assessment Link", {"fields": ["assessment", "created_at", "updated_at"]}),
        ("Severity Levels", {"fields": ["depression_level", "anxiety_level", "stress_level"]}),
        ("Emotion Data", {"fields": ["dominant_emotion", "scale_emotions", "emotional_summary", "emotion_labels", "facial_note"]}),
        ("Recommendations", {"fields": ["recommendations_json"]}),
        ("Session Comparison", {"fields": ["past_sessions_found", "overall_trend", "comparison_summary", "comparison_results"]}),
        # ── The new field ──────────────────────────────────────────────────
        ("🤖 Therapist Script (AI Generated)", {
            "fields": ["therapist_script"],
            "description": (
                "Auto-generated by Gemini 2.0 Flash from the full analysis result. "
                "Check this field to verify quality before surfacing it to students."
            ),
        }),
    ]
 
    @admin.display(boolean=True, description="Has Script?")
    def has_therapist_script(self, obj):
        return bool(obj.therapist_script)