# Generated by Django 6.0.1 on 2026-03-01 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('video_file', models.CharField(max_length=255)),
                ('question_text', models.TextField(blank=True)),
                ('mse_category', models.CharField(blank=True, max_length=100)),
                ('is_final', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('assessment_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('report_generated_at', models.DateTimeField(blank=True, null=True)),
                ('report_text', models.TextField(blank=True)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_emotion', models.CharField(blank=True, max_length=32)),
                ('emotion_scores', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('no_face', 'No Face'), ('error', 'Error'), ('quality_low', 'Quality Low'), ('rate_limited', 'Rate Limited')], default='ok', max_length=16)),
                ('client_ts', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_records', to='Questionaire_project.assessment')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emotion_records', to='Questionaire_project.question')),
            ],
            options={
                'indexes': [models.Index(fields=['assessment', 'created_at'], name='Questionair_assessm_a77aec_idx'), models.Index(fields=['question', 'created_at'], name='Questionair_questio_bb8cdf_idx'), models.Index(fields=['status'], name='Questionair_status_28fe70_idx')],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Questionaire_project.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='Questionaire_project.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assessment', 'question'), name='uq_assessment_question')],
            },
        ),
    ]
