# Generated by Django 5.1.7 on 2026-03-13 12:00

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("Questionaire_project", "0002_answer_answer_score_assessment_anxiety_result_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotionrecord",
            name="frame_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="emotionrecord",
            name="scale",
            field=models.CharField(
                blank=True,
                choices=[
                    ("depression", "Depression (BDI)"),
                    ("stress", "Stress (PSS-10)"),
                    ("anxiety", "Anxiety (BAI)"),
                    ("title", "Title Screen"),
                    ("final", "Final Screen"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ScaleEmotionSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scale", models.CharField(choices=[("depression", "Depression (BDI)"), ("stress", "Stress (PSS-10)"), ("anxiety", "Anxiety (BAI)"), ("title", "Title Screen"), ("final", "Final Screen")], db_index=True, max_length=20)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_frames", models.PositiveIntegerField(default=0)),
                ("overall_dominant_emotion", models.CharField(blank=True, max_length=32)),
                ("distress_ratio", models.FloatField(blank=True, null=True)),
                ("assessment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scale_emotion_sessions", to="Questionaire_project.assessment")),
            ],
        ),
        migrations.AddIndex(
            model_name="emotionrecord",
            index=models.Index(fields=["assessment", "scale", "created_at"], name="Questionair_assessm_a4aa09_idx"),
        ),
        migrations.AddIndex(
            model_name="scaleemotionsession",
            index=models.Index(fields=["assessment", "scale", "started_at"], name="Questionair_assessm_70fce0_idx"),
        ),
        migrations.AddConstraint(
            model_name="emotionrecord",
            constraint=models.UniqueConstraint(condition=~Q(frame_id=""), fields=("assessment", "scale", "frame_id"), name="uq_emotionrecord_assessment_scale_frame"),
        ),
    ]
