# Generated by Django 6.0.1 on 2026-02-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire_project', '0002_assessment_is_completed_emotionrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emotionrecord',
            new_name='Questionair_assessm_a77aec_idx',
            old_name='Questionair_assessm_62dc28_idx',
        ),
        migrations.RenameIndex(
            model_name='emotionrecord',
            new_name='Questionair_questio_bb8cdf_idx',
            old_name='Questionair_question_5ab645_idx',
        ),
        migrations.RenameIndex(
            model_name='emotionrecord',
            new_name='Questionair_status_28fe70_idx',
            old_name='Questionair_status_b3c58a_idx',
        ),
    ]
