# Generated by Django 6.0.1 on 2026-03-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire_project', '0003_scale_emotion_session_and_scale_streaming'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emotionrecord',
            new_name='Questionair_assessm_81627d_idx',
            old_name='Questionair_assessm_a4aa09_idx',
        ),
        migrations.RenameIndex(
            model_name='scaleemotionsession',
            new_name='Questionair_assessm_f8c9ec_idx',
            old_name='Questionair_assessm_70fce0_idx',
        ),
    ]
