# Generated by Django 6.0.1 on 2026-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire_project', '0004_rename_questionair_assessm_a4aa09_idx_questionair_assessm_81627d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='questionnaire_project_final_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questionnaire_project_final_score',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questionnaire_project_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
