# Generated by Django 5.1.7 on 2026-03-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire_project', '0005_assessment_questionnaire_project_final_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionrecord',
            name='scale',
            field=models.CharField(blank=True, choices=[('depression', 'Depression (BDI)'), ('stress', 'Stress (PSS-10)'), ('anxiety', 'Anxiety (BAI)'), ('title', 'Title Screen'), ('final', 'Final Screen'), ('open_ended', 'Open Ended Reflection')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='scale',
            field=models.CharField(blank=True, choices=[('depression', 'Depression (BDI)'), ('stress', 'Stress (PSS-10)'), ('anxiety', 'Anxiety (BAI)'), ('title', 'Title Screen'), ('final', 'Final Screen'), ('open_ended', 'Open Ended Reflection')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='scaleemotionsession',
            name='scale',
            field=models.CharField(choices=[('depression', 'Depression (BDI)'), ('stress', 'Stress (PSS-10)'), ('anxiety', 'Anxiety (BAI)'), ('title', 'Title Screen'), ('final', 'Final Screen'), ('open_ended', 'Open Ended Reflection')], db_index=True, max_length=20),
        ),
    ]
