# Generated by Django 5.1.7 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Questionaire_project", "0007_alter_emotionrecord_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emotionrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "OK"),
                    ("no_face", "No Face"),
                    ("error", "Error"),
                    ("quality_low", "Quality Low"),
                    ("rate_limited", "Rate Limited"),
                    ("fallback", "Fallback"),
                    ("repaired", "Repaired"),
                ],
                default="ok",
                max_length=16,
            ),
        ),
    ]
