# Generated by Django 5.1.7 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Questionaire_project", "0008_alter_emotionrecord_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotionrecord",
            name="frame_number",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="emotionrecord",
            name="timestamp_sec",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="emotionrecord",
            index=models.Index(fields=["assessment", "scale", "frame_number"], name="Questionair_assessm_4e952a_idx"),
        ),
        migrations.RemoveConstraint(
            model_name="emotionrecord",
            name="uq_emotionrecord_assessment_scale_frame",
        ),
    ]
