# Generated by Django 5.1.7 on 2026-04-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire_project', '0010_alter_emotionrecord_status_add_uncertain'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emotionrecord',
            new_name='Questionair_assessm_d506bf_idx',
            old_name='Questionair_assessm_4e952a_idx',
        ),
    ]
