# Generated by Django 5.1.7 on 2026-04-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire_project', '0011_rename_questionair_assessm_4e952a_idx_questionair_assessm_d506bf_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSEReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_html', models.TextField(blank=True)),
                ('report_pdf', models.BinaryField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mse_report', to='Questionaire_project.assessment')),
            ],
        ),
    ]
