# Generated by Django 5.1.7 on 2026-04-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire_project', '0012_msereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depression_level', models.CharField(blank=True, default='', help_text='Severity level: low | moderate | severe', max_length=20)),
                ('anxiety_level', models.CharField(blank=True, default='', max_length=20)),
                ('stress_level', models.CharField(blank=True, default='', max_length=20)),
                ('dominant_emotion', models.CharField(blank=True, default='', help_text='Overall dominant emotion: sad | fear | angry | disgust | surprise | neutral | happy', max_length=32)),
                ('scale_emotions', models.JSONField(blank=True, default=dict, help_text='Per-scale dominant emotion. e.g. {"depression": "sad", "stress": "angry"}')),
                ('emotional_summary', models.TextField(blank=True, default='', help_text="Free-text summary from the student's open-ended reflection (feeling_analysis).")),
                ('emotion_labels', models.JSONField(blank=True, default=list, help_text='Concern labels from feeling_analysis. e.g. ["loneliness", "academic_stress"]')),
                ('emotion_conditions', models.JSONField(blank=True, default=list, help_text='Mental health conditions mapped from the dominant emotion.')),
                ('facial_note', models.TextField(blank=True, default='', help_text='Human-readable note explaining what the facial expression result means.')),
                ('recommendations_json', models.JSONField(blank=True, default=dict, help_text="Full recommendations block for all three scales. e.g. {'depression': {'level': 'moderate', 'tips': [...], 'message': '...'}, ...}")),
                ('consoling_summary_response', models.TextField(blank=True, default='', help_text="Empathetic response to the student's emotional summary text.")),
                ('consoling_label_responses', models.JSONField(blank=True, default=dict, help_text='Per-label consoling messages. e.g. {"loneliness": "You are not alone..."}')),
                ('consoling_combined_message', models.TextField(blank=True, default='', help_text='One unified empathetic closing message for the student.')),
                ('past_sessions_found', models.PositiveSmallIntegerField(default=0, help_text='Number of past completed sessions found (0, 1, or 2).')),
                ('comparison_results', models.JSONField(blank=True, default=list, help_text='List of comparison dicts, one per past session.')),
                ('overall_trend', models.CharField(blank=True, default='no_data', help_text='Trend across sessions: improving | worsening | stable | mixed | no_data', max_length=20)),
                ('comparison_summary', models.TextField(blank=True, default='', help_text='Human-readable paragraph summarising the trend across past sessions.')),
                ('assessment', models.OneToOneField(help_text='The completed assessment this result belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='Questionaire_project.assessment')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
