# Generated by Django 5.1.7 on 2026-04-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire_project', '0013_analysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='therapist_script',
            field=models.TextField(blank=True, default='', help_text='AI-generated conversational therapist monologue based on full analysis.'),
        ),
    ]
