# Generated by Django 5.1.7 on 2026-04-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire_project', '0014_analysisresult_therapist_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='consoling_combined_message',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='consoling_label_responses',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='consoling_summary_response',
        ),
    ]
